spring:
  cloud:
    stream:
      function:
        definition: orderSupplier;paymentEventConsumer # look in purchase order config bean
      bindings:
        orderSupplier-out-0:
          destination: order-event
        paymentEventConsumer-in-0:
          destination: payment-event

